import type { Recipe, RemixReview } from './types';

export const initialRecipesData: Recipe[] = [
    { id: 1, title: "Banana Peel 'Pulled Pork' Sandwich", image: "https://art.whisk.com/image/upload/fl_progressive,h_600,w_800,c_fill/v1620708148/recipe/06bc6d45f47cdb3b13e17e75acbbc9d2.jpg", time: "25 min", difficulty: 'Medium', category: 'Lunch', cuisine: 'Fusion', ingredients: "2 banana peels\n1 tbsp olive oil\n1/2 onion, sliced\nBBQ sauce\nBurger bun", steps: "1. Shred banana peels with a fork.\n2. Sauté with sliced onion in olive oil until soft.\n3. Stir in BBQ sauce and simmer for 5-10 minutes.\n4. Serve on a toasted bun.", remixNotes: "Great way to use banana peels you'd otherwise throw out. Add a pinch of smoked paprika for extra flavor. Works with leftover tortillas too!", likes: 12, saves: 5 },
    { id: 2, title: "Stale Bread Croutons", image: "https://www.twopeasandtheirpod.com/wp-content/uploads/2019/05/Croutons-3-650x433.jpg", time: "15 min", difficulty: 'Easy', category: 'Snacks', cuisine: 'Italian', ingredients: "Stale bread, cubed\nOlive oil\nHerbs (rosemary, thyme)\nSalt & Pepper", steps: "1. Preheat oven to 375°F (190°C).\n2. Toss cubed bread with olive oil, herbs, salt, and pepper.\n3. Spread on a baking sheet.\n4. Bake for 10-15 minutes, or until golden and crispy.", remixNotes: "Perfect for soups and salads. You can also add garlic powder or parmesan cheese before baking. Any old bread works!", likes: 25, saves: 11 },
    { id: 3, title: "Broccoli Stem Pesto Pasta", image: "https://www.gimmesomeoven.com/wp-content/uploads/2024/02/Lemon-Broccoli-Pasta-Recipe-9.jpg", time: "20 min", difficulty: 'Easy', category: 'Dinner', cuisine: 'Italian', ingredients: "Broccoli stems, chopped\nGarlic clove\nHandful of pine nuts or walnuts\nParmesan cheese\nOlive oil\nCooked pasta", steps: "1. Chop broccoli stems into small pieces.\n2. Blend stems, garlic, nuts, and parmesan in a food processor.\n3. Drizzle in olive oil while blending until smooth.\n4. Toss with freshly cooked pasta.", remixNotes: "Don't waste those stems! This pesto is also great on toast or as a sandwich spread. You can substitute spinach for half the broccoli stems.", likes: 18, saves: 9 },
    { id: 4, title: "Leftover Rice Breakfast Porridge", image: "https://hips.hearstapps.com/hmg-prod/images/oatmeal-porridge-with-apple-cinnamon-and-royalty-free-image-1617356585.?crop=0.668xw:1.00xh;0.150xw,0&resize=640:*", time: "10 min", difficulty: 'Easy', category: 'Breakfast', cuisine: 'Fusion', ingredients: "1 cup cooked rice\n1.5 cups milk (any kind)\n1 tbsp maple syrup or honey\nCinnamon\nFruits for topping", steps: "1. Combine leftover rice and milk in a small pot.\n2. Simmer over medium heat, stirring occasionally, until it thickens into a porridge consistency (about 5-7 minutes).\n3. Stir in sweetener and a dash of cinnamon.\n4. Top with your favorite fruits, nuts, or seeds.", remixNotes: "A quick and comforting breakfast. Works with any type of plain leftover rice (white, brown, jasmine). Add a spoonful of peanut butter for extra protein.", likes: 32, saves: 15 },
    { id: 5, title: "Spicy Roasted Chickpeas", image: "https://www.eatingwell.com/thmb/U9XX4O3Ds4geco7uTt-t6LeKsYE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Spice-Roasted-Chickpeas-2-454859750de34b71bb8c900d35852844.jpg", time: "30 min", difficulty: 'Easy', category: 'Snacks', cuisine: 'Indian', ingredients: "1 can chickpeas, rinsed and dried\n1 tbsp olive oil\n1 tsp chili powder\n1/2 tsp cumin\nSalt to taste", steps: "1. Preheat oven to 400°F (200°C).\n2. Pat chickpeas very dry.\n3. Toss with olive oil and spices.\n4. Roast for 20-25 minutes, until crispy.", remixNotes: "A healthy, crunchy snack. Use any spices you have on hand - curry powder or smoked paprika are great alternatives.", likes: 45, saves: 22 },
    { id: 6, title: "Veggie Scrap Broth", image: "https://img.buzzfeed.com/video-api-prod/assets/f00660d8d9ad4c73b0d28cd050b9d7ef/Thumb1.jpg?resize=1200:*", time: "1 hour", difficulty: 'Easy', category: 'Dinner', cuisine: 'Continental', ingredients: "Onion peels\nCarrot ends and peels\nCelery ends\nHerb stems (parsley, cilantro)\nWater", steps: "1. Collect veggie scraps in a bag in the freezer.\n2. When you have a full bag, add to a large pot and cover with water.\n3. Simmer for at least an hour.\n4. Strain out the scraps and store the broth.", remixNotes: "The ultimate waste-free recipe! Use this nutritious broth as a base for soups, stews, or for cooking grains like rice and quinoa.", likes: 50, saves: 30 },
    { id: 7, title: "Spiced Watermelon Rind Curry", image: "https://www.thepeppercook.com/wp-content/uploads/2020/05/watermeloncurryindex-1.1-scaled.jpg", time: "35 min", difficulty: 'Medium', category: 'Dinner', cuisine: 'Indian', ingredients: "Rind from 1/4 watermelon\n1 onion, chopped\n1 tomato, chopped\n1 tsp ginger-garlic paste\nSpices (turmeric, chili powder, coriander)\nCoconut milk (optional)", steps: "1. Peel the green skin off the rind and chop the white part.\n2. Sauté onion, then add ginger-garlic paste and tomatoes.\n3. Add spices and cook for 2 minutes.\n4. Add watermelon rind, water, and cook until tender.\n5. Finish with coconut milk if desired.", remixNotes: "A surprisingly delicious way to use the entire watermelon! The rind has a texture similar to squash. Great with rice or roti.", likes: 28, saves: 14 },
    { id: 8, title: "Crispy Potato Peel Snacks", image: "https://www.worldofvegan.com/wp-content/uploads/2021/11/potato-skin-chips.jpg", time: "20 min", difficulty: 'Easy', category: 'Snacks', cuisine: 'Fusion', ingredients: "Peels from 4-5 potatoes\n1 tbsp olive oil\nSalt, pepper, paprika", steps: "1. Wash potato peels thoroughly and pat dry.\n2. Toss with olive oil and seasonings.\n3. Spread on a baking sheet in a single layer.\n4. Bake at 400°F (200°C) for 15-20 minutes, flipping halfway, until crispy.", remixNotes: "Never throw away potato peels again! These are addictive. Serve with a yogurt dip or ketchup.", likes: 41, saves: 25 },
    { id: 9, title: "Leftover Pasta Frittata", image: "https://www.saveur.com/uploads/2022/10/16/Saveur_OPB_Feature_PastaFrittata_Vertical.jpg?format=webp&optimize=high&precrop=4%3A3%2Csmart", time: "25 min", difficulty: 'Easy', category: 'Breakfast', cuisine: 'Italian', ingredients: "2 cups leftover cooked pasta\n6 eggs, beaten\n1/2 cup cheese, grated\nAny leftover veggies or meat\nSalt & pepper", steps: "1. Preheat oven to 375°F (190°C).\n2. Mix all ingredients in a bowl.\n3. Pour into a greased, oven-safe skillet.\n4. Bake for 15-20 minutes until the center is set.\n5. Slice and serve warm or cold.", remixNotes: "Transforms leftover pasta into a completely new meal. Perfect for breakfast, lunch, or a light dinner. Almost any leftover pasta works.", likes: 35, saves: 18 },
    { id: 10, title: "Aquafaba Chocolate Mousse", image: "https://cookingwithelo.com/wp-content/uploads/2021/12/Aquafaba-chocolate-mousse.jpg", time: "15 min + chilling", difficulty: 'Medium', category: 'Dinner', cuisine: 'Fusion', ingredients: "Liquid from 1 can of chickpeas (aquafaba)\n100g dark chocolate, melted\n1 tbsp powdered sugar (optional)\n1/2 tsp vanilla extract", steps: "1. Whip the chickpea liquid (aquafaba) with an electric mixer until stiff peaks form (like egg whites).\n2. Gently fold in the melted (and cooled) dark chocolate and vanilla.\n3. Spoon into glasses and chill for at least 1 hour.\n4. Serve and be amazed!", remixNotes: "Don't pour that chickpea water down the drain! Aquafaba is a magical vegan egg replacer. This mousse is rich, airy, and a total crowd-pleaser.", likes: 48, saves: 28 },
];

export const initialRemixReviewsData: RemixReview[] = [
    { id: 'remix1', recipeId: 1, reviewerName: 'WasteWarrior', tip: "Added a splash of liquid smoke with the BBQ sauce. It takes the 'pulled pork' flavor to the next level!", timestamp: Date.now() - 86400000, upvotes: 5 },
    { id: 'remix2', recipeId: 1, reviewerName: 'EcoEats', tip: "I served this on leftover tortillas instead of buns and it was amazing. Less waste!", timestamp: Date.now() - 172800000, upvotes: 12 },
    { id: 'remix3', recipeId: 2, reviewerName: 'CrunchMaster', tip: "A pinch of cayenne pepper gives these croutons a nice kick.", timestamp: Date.now() - 3600000, upvotes: 8 },
];

export const getOrCreateUserId = (): string => {
    let userId = localStorage.getItem('plateMateUserId');
    if (!userId) {
        userId = `user_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
        localStorage.setItem('plateMateUserId', userId);
    }
    return userId;
};